#############################################################################
# Makefile for building: code
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  code.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile code.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = code1.0.0
DISTDIR = /home/xmy/code/.tmp/code1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qt_signal_slot_test.cpp \
		test_client.cpp \
		test_login.cpp \
		test_signal_slot.cpp \
		src/chatclient.cpp \
		src/chatserver.cpp \
		src/chatwindow.cpp \
		src/loginwindow.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		build/rcc/qrc_qtchat.cpp \
		src/client/main.cpp \
		src/db/db.cpp \
		src/models/friendmodel.cpp \
		src/models/groupmodel.cpp \
		src/models/offlinemessagemodel.cpp \
		src/models/usermodel.cpp \
		src/server/chatserver.cpp \
		src/server/chatservice.cpp \
		src/server/main.cpp \
		test/testjson/obtestjson.cpp \
		test/testjson/testjson.cpp \
		test/testmuduo/muduo_server.cpp \
		src/server/db/db.cpp \
		src/server/model/friendmodel.cpp \
		src/server/model/groupmodel.cpp \
		src/server/model/offlinemessagemodel.cpp \
		src/server/model/usermodel.cpp \
		src/server/redis/redis.cpp \
		build/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
		build/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
		build/src/client/ChatClient_autogen/mocs_compilation.cpp \
		build/src/client/QtChat_autogen/mocs_compilation.cpp \
		build/src/server/ChatServer_autogen/mocs_compilation.cpp \
		test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
		test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp qrc_qtchat.cpp \
		moc_chatclient.cpp \
		moc_chatserver.cpp \
		moc_chatwindow.cpp \
		moc_loginwindow.cpp \
		moc_mainwindow.cpp
OBJECTS       = qt_signal_slot_test.o \
		test_client.o \
		test_login.o \
		test_signal_slot.o \
		chatclient.o \
		chatserver.o \
		chatwindow.o \
		loginwindow.o \
		main.o \
		mainwindow.o \
		qrc_qtchat.o \
		main.o \
		db.o \
		friendmodel.o \
		groupmodel.o \
		offlinemessagemodel.o \
		usermodel.o \
		chatserver.o \
		chatservice.o \
		main.o \
		obtestjson.o \
		testjson.o \
		muduo_server.o \
		db.o \
		friendmodel.o \
		groupmodel.o \
		offlinemessagemodel.o \
		usermodel.o \
		redis.o \
		CMakeCCompilerId.o \
		CMakeCXXCompilerId.o \
		mocs_compilation.o \
		mocs_compilation.o \
		mocs_compilation.o \
		CMakeCCompilerId.o \
		CMakeCXXCompilerId.o \
		qrc_qtchat.o \
		moc_chatclient.o \
		moc_chatserver.o \
		moc_chatwindow.o \
		moc_loginwindow.o \
		moc_mainwindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		code.pro include/public.hpp \
		src/chatclient.h \
		src/chatserver.h \
		src/chatwindow.h \
		src/loginwindow.h \
		src/mainwindow.h \
		src/public.h \
		thirdparty/json.hpp \
		include/server/chatserver.hpp \
		include/server/chatservice.hpp \
		src/db/db.h \
		src/models/friendmodel.h \
		src/models/group.h \
		src/models/groupmodel.h \
		src/models/groupuser.h \
		src/models/offlinemessagemodel.h \
		src/models/user.h \
		src/models/usermodel.h \
		test/testjson/json.hpp \
		include/server/db/db.h \
		include/server/model/friendmodel.hpp \
		include/server/model/group.hpp \
		include/server/model/groupmodel.hpp \
		include/server/model/groupuser.hpp \
		include/server/model/offlinemessagemodel.hpp \
		include/server/model/user.hpp \
		include/server/model/UserModel.hpp \
		include/server/redis/redis.hpp qt_signal_slot_test.cpp \
		test_client.cpp \
		test_login.cpp \
		test_signal_slot.cpp \
		src/chatclient.cpp \
		src/chatserver.cpp \
		src/chatwindow.cpp \
		src/loginwindow.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		build/rcc/qrc_qtchat.cpp \
		src/client/main.cpp \
		src/db/db.cpp \
		src/models/friendmodel.cpp \
		src/models/groupmodel.cpp \
		src/models/offlinemessagemodel.cpp \
		src/models/usermodel.cpp \
		src/server/chatserver.cpp \
		src/server/chatservice.cpp \
		src/server/main.cpp \
		test/testjson/obtestjson.cpp \
		test/testjson/testjson.cpp \
		test/testmuduo/muduo_server.cpp \
		src/server/db/db.cpp \
		src/server/model/friendmodel.cpp \
		src/server/model/groupmodel.cpp \
		src/server/model/offlinemessagemodel.cpp \
		src/server/model/usermodel.cpp \
		src/server/redis/redis.cpp \
		build/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
		build/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
		build/src/client/ChatClient_autogen/mocs_compilation.cpp \
		build/src/client/QtChat_autogen/mocs_compilation.cpp \
		build/src/server/ChatServer_autogen/mocs_compilation.cpp \
		test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
		test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
QMAKE_TARGET  = code
DESTDIR       = 
TARGET        = code


first: all
####### Build rules

code:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: code.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		code.pro \
		src/qtchat.qrc
	$(QMAKE) -o Makefile code.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
code.pro:
src/qtchat.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile code.pro

qmake_all: FORCE


all: Makefile code

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/qtchat.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/public.hpp src/chatclient.h src/chatserver.h src/chatwindow.h src/loginwindow.h src/mainwindow.h src/public.h thirdparty/json.hpp include/server/chatserver.hpp include/server/chatservice.hpp src/db/db.h src/models/friendmodel.h src/models/group.h src/models/groupmodel.h src/models/groupuser.h src/models/offlinemessagemodel.h src/models/user.h src/models/usermodel.h test/testjson/json.hpp include/server/db/db.h include/server/model/friendmodel.hpp include/server/model/group.hpp include/server/model/groupmodel.hpp include/server/model/groupuser.hpp include/server/model/offlinemessagemodel.hpp include/server/model/user.hpp include/server/model/UserModel.hpp include/server/redis/redis.hpp $(DISTDIR)/
	$(COPY_FILE) --parents qt_signal_slot_test.cpp test_client.cpp test_login.cpp test_signal_slot.cpp src/chatclient.cpp src/chatserver.cpp src/chatwindow.cpp src/loginwindow.cpp src/main.cpp src/mainwindow.cpp build/rcc/qrc_qtchat.cpp src/client/main.cpp src/db/db.cpp src/models/friendmodel.cpp src/models/groupmodel.cpp src/models/offlinemessagemodel.cpp src/models/usermodel.cpp src/server/chatserver.cpp src/server/chatservice.cpp src/server/main.cpp test/testjson/obtestjson.cpp test/testjson/testjson.cpp test/testmuduo/muduo_server.cpp src/server/db/db.cpp src/server/model/friendmodel.cpp src/server/model/groupmodel.cpp src/server/model/offlinemessagemodel.cpp src/server/model/usermodel.cpp src/server/redis/redis.cpp build/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c build/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp build/src/client/ChatClient_autogen/mocs_compilation.cpp build/src/client/QtChat_autogen/mocs_compilation.cpp build/src/server/ChatServer_autogen/mocs_compilation.cpp test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp $(DISTDIR)/
	$(COPY_FILE) --parents build/src/client/CMakeFiles/ChatClient.dir/compiler_depend.ts build/src/client/CMakeFiles/ChatClient_autogen.dir/compiler_depend.ts build/src/client/CMakeFiles/ChatClient_autogen_timestamp_deps.dir/compiler_depend.ts build/src/client/CMakeFiles/QtChat.dir/compiler_depend.ts build/src/client/CMakeFiles/QtChat_autogen.dir/compiler_depend.ts build/src/client/CMakeFiles/QtChat_autogen_timestamp_deps.dir/compiler_depend.ts build/src/server/CMakeFiles/ChatServer.dir/compiler_depend.ts build/src/server/CMakeFiles/ChatServer_autogen.dir/compiler_depend.ts build/src/server/CMakeFiles/ChatServer_autogen_timestamp_deps.dir/compiler_depend.ts test/testmuduo/bulid/CMakeFiles/server.dir/compiler_depend.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qtchat.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qtchat.cpp
qrc_qtchat.cpp: src/qtchat.qrc \
		/usr/lib/qt5/bin/rcc \
		src/icons/send.png \
		src/icons/chat.png \
		src/icons/add.png \
		src/icons/user.png \
		src/icons/exit.png \
		src/icons/group.png \
		src/icons/refresh.png
	/usr/lib/qt5/bin/rcc -name qtchat src/qtchat.qrc -o qrc_qtchat.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_chatclient.cpp moc_chatserver.cpp moc_chatwindow.cpp moc_loginwindow.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_chatclient.cpp moc_chatserver.cpp moc_chatwindow.cpp moc_loginwindow.cpp moc_mainwindow.cpp
moc_chatclient.cpp: src/chatclient.h \
		src/public.h \
		src/models/user.h \
		src/models/group.h \
		src/models/groupuser.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/xmy/code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/xmy/code -I/home/xmy/code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/xmy/muduo -I. -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/chatclient.h -o moc_chatclient.cpp

moc_chatserver.cpp: src/chatserver.h \
		src/models/usermodel.h \
		src/models/user.h \
		src/models/friendmodel.h \
		src/models/groupmodel.h \
		src/models/group.h \
		src/models/groupuser.h \
		src/models/offlinemessagemodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/xmy/code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/xmy/code -I/home/xmy/code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/xmy/muduo -I. -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/chatserver.h -o moc_chatserver.cpp

moc_chatwindow.cpp: src/chatwindow.h \
		src/chatclient.h \
		src/public.h \
		src/models/user.h \
		src/models/group.h \
		src/models/groupuser.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/xmy/code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/xmy/code -I/home/xmy/code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/xmy/muduo -I. -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/chatwindow.h -o moc_chatwindow.cpp

moc_loginwindow.cpp: src/loginwindow.h \
		src/chatclient.h \
		src/public.h \
		src/models/user.h \
		src/models/group.h \
		src/models/groupuser.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/xmy/code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/xmy/code -I/home/xmy/code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/xmy/muduo -I. -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/loginwindow.h -o moc_loginwindow.cpp

moc_mainwindow.cpp: src/mainwindow.h \
		src/chatserver.h \
		src/models/usermodel.h \
		src/models/user.h \
		src/models/friendmodel.h \
		src/models/groupmodel.h \
		src/models/group.h \
		src/models/groupuser.h \
		src/models/offlinemessagemodel.h \
		src/loginwindow.h \
		src/chatclient.h \
		src/public.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/xmy/code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/xmy/code -I/home/xmy/code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/home/xmy/muduo -I. -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

qt_signal_slot_test.o: qt_signal_slot_test.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt_signal_slot_test.o qt_signal_slot_test.cpp

test_client.o: test_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test_client.o test_client.cpp

test_login.o: test_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test_login.o test_login.cpp

test_signal_slot.o: test_signal_slot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test_signal_slot.o test_signal_slot.cpp

chatclient.o: src/chatclient.cpp src/chatclient.h \
		src/public.h \
		src/models/user.h \
		src/models/group.h \
		src/models/groupuser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatclient.o src/chatclient.cpp

chatserver.o: src/chatserver.cpp src/chatserver.h \
		src/models/usermodel.h \
		src/models/user.h \
		src/models/friendmodel.h \
		src/models/groupmodel.h \
		src/models/group.h \
		src/models/groupuser.h \
		src/models/offlinemessagemodel.h \
		src/public.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatserver.o src/chatserver.cpp

chatwindow.o: src/chatwindow.cpp src/chatwindow.h \
		src/chatclient.h \
		src/public.h \
		src/models/user.h \
		src/models/group.h \
		src/models/groupuser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatwindow.o src/chatwindow.cpp

loginwindow.o: src/loginwindow.cpp src/loginwindow.h \
		src/chatclient.h \
		src/public.h \
		src/models/user.h \
		src/models/group.h \
		src/models/groupuser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwindow.o src/loginwindow.cpp

main.o: src/main.cpp src/loginwindow.h \
		src/chatclient.h \
		src/public.h \
		src/models/user.h \
		src/models/group.h \
		src/models/groupuser.h \
		src/chatwindow.h \
		src/db/db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/chatserver.h \
		src/models/usermodel.h \
		src/models/user.h \
		src/models/friendmodel.h \
		src/models/groupmodel.h \
		src/models/group.h \
		src/models/groupuser.h \
		src/models/offlinemessagemodel.h \
		src/loginwindow.h \
		src/chatclient.h \
		src/public.h \
		src/chatwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

qrc_qtchat.o: build/rcc/qrc_qtchat.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qtchat.o build/rcc/qrc_qtchat.cpp

main.o: src/client/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/client/main.cpp

db.o: src/db/db.cpp src/db/db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db.o src/db/db.cpp

friendmodel.o: src/models/friendmodel.cpp src/models/friendmodel.h \
		src/models/user.h \
		src/db/db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o friendmodel.o src/models/friendmodel.cpp

groupmodel.o: src/models/groupmodel.cpp src/models/groupmodel.h \
		src/models/group.h \
		src/models/groupuser.h \
		src/models/user.h \
		src/db/db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groupmodel.o src/models/groupmodel.cpp

offlinemessagemodel.o: src/models/offlinemessagemodel.cpp src/models/offlinemessagemodel.h \
		src/db/db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o offlinemessagemodel.o src/models/offlinemessagemodel.cpp

usermodel.o: src/models/usermodel.cpp src/models/usermodel.h \
		src/models/user.h \
		src/db/db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usermodel.o src/models/usermodel.cpp

chatserver.o: src/server/chatserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatserver.o src/server/chatserver.cpp

chatservice.o: src/server/chatservice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chatservice.o src/server/chatservice.cpp

main.o: src/server/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/server/main.cpp

obtestjson.o: test/testjson/obtestjson.cpp test/testjson/json.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obtestjson.o test/testjson/obtestjson.cpp

testjson.o: test/testjson/testjson.cpp test/testjson/json.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testjson.o test/testjson/testjson.cpp

muduo_server.o: test/testmuduo/muduo_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o muduo_server.o test/testmuduo/muduo_server.cpp

db.o: src/server/db/db.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db.o src/server/db/db.cpp

friendmodel.o: src/server/model/friendmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o friendmodel.o src/server/model/friendmodel.cpp

groupmodel.o: src/server/model/groupmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groupmodel.o src/server/model/groupmodel.cpp

offlinemessagemodel.o: src/server/model/offlinemessagemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o offlinemessagemodel.o src/server/model/offlinemessagemodel.cpp

usermodel.o: src/server/model/usermodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usermodel.o src/server/model/usermodel.cpp

redis.o: src/server/redis/redis.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o redis.o src/server/redis/redis.cpp

CMakeCCompilerId.o: build/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o CMakeCCompilerId.o build/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c

CMakeCXXCompilerId.o: build/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CMakeCXXCompilerId.o build/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp

mocs_compilation.o: build/src/client/ChatClient_autogen/mocs_compilation.cpp build/src/client/ChatClient_autogen/VNU7RW3YIC/moc_chatclient.cpp \
		src/chatclient.h \
		src/public.h \
		src/models/user.h \
		src/models/group.h \
		src/models/groupuser.h \
		build/src/client/ChatClient_autogen/VNU7RW3YIC/moc_chatserver.cpp \
		src/chatserver.h \
		src/models/usermodel.h \
		src/models/friendmodel.h \
		src/models/groupmodel.h \
		src/models/offlinemessagemodel.h \
		build/src/client/ChatClient_autogen/VNU7RW3YIC/moc_chatwindow.cpp \
		src/chatwindow.h \
		build/src/client/ChatClient_autogen/VNU7RW3YIC/moc_loginwindow.cpp \
		src/loginwindow.h \
		build/src/client/ChatClient_autogen/VNU7RW3YIC/moc_mainwindow.cpp \
		src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mocs_compilation.o build/src/client/ChatClient_autogen/mocs_compilation.cpp

mocs_compilation.o: build/src/client/QtChat_autogen/mocs_compilation.cpp build/src/client/QtChat_autogen/VNU7RW3YIC/moc_chatclient.cpp \
		src/chatclient.h \
		src/public.h \
		src/models/user.h \
		src/models/group.h \
		src/models/groupuser.h \
		build/src/client/QtChat_autogen/VNU7RW3YIC/moc_chatserver.cpp \
		src/chatserver.h \
		src/models/usermodel.h \
		src/models/friendmodel.h \
		src/models/groupmodel.h \
		src/models/offlinemessagemodel.h \
		build/src/client/QtChat_autogen/VNU7RW3YIC/moc_chatwindow.cpp \
		src/chatwindow.h \
		build/src/client/QtChat_autogen/VNU7RW3YIC/moc_loginwindow.cpp \
		src/loginwindow.h \
		build/src/client/QtChat_autogen/VNU7RW3YIC/moc_mainwindow.cpp \
		src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mocs_compilation.o build/src/client/QtChat_autogen/mocs_compilation.cpp

mocs_compilation.o: build/src/server/ChatServer_autogen/mocs_compilation.cpp build/src/server/ChatServer_autogen/VNU7RW3YIC/moc_chatserver.cpp \
		src/chatserver.h \
		src/models/usermodel.h \
		src/models/user.h \
		src/models/friendmodel.h \
		src/models/groupmodel.h \
		src/models/group.h \
		src/models/groupuser.h \
		src/models/offlinemessagemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mocs_compilation.o build/src/server/ChatServer_autogen/mocs_compilation.cpp

CMakeCCompilerId.o: test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o CMakeCCompilerId.o test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c

CMakeCXXCompilerId.o: test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CMakeCXXCompilerId.o test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp

qrc_qtchat.o: qrc_qtchat.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qtchat.o qrc_qtchat.cpp

moc_chatclient.o: moc_chatclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chatclient.o moc_chatclient.cpp

moc_chatserver.o: moc_chatserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chatserver.o moc_chatserver.cpp

moc_chatwindow.o: moc_chatwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chatwindow.o moc_chatwindow.cpp

moc_loginwindow.o: moc_loginwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginwindow.o moc_loginwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

