######################################################################
# Automatically generated by qmake (3.1) Tue Jan 13 23:37:43 2026
######################################################################

TEMPLATE = app
TARGET = qtchat_client_temp
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += include/public.hpp \
           src/chatclient.h \
           src/chatserver.h \
           src/chatwindow.h \
           src/loginwindow.h \
           src/mainwindow.h \
           src/messagewidget.h \
           src/public.h \
           thirdparty/json.hpp \
           include/server/chatserver.hpp \
           include/server/chatservice.hpp \
           src/db/db.h \
           src/models/friendmodel.h \
           src/models/group.h \
           src/models/groupmodel.h \
           src/models/groupuser.h \
           src/models/user.h \
           src/models/usermodel.h \
           test/testjson/json.hpp \
           include/server/db/db.h \
           include/server/model/emoji.hpp \
           include/server/model/emojimodel.hpp \
           include/server/model/friendmodel.hpp \
           include/server/model/group.hpp \
           include/server/model/groupmodel.hpp \
           include/server/model/groupuser.hpp \
           include/server/model/offlinemessagemodel.hpp \
           include/server/model/user.hpp \
           include/server/model/UserModel.hpp \
           include/server/redis/redis.hpp
SOURCES += test_avatar_decoding.cpp \
           src/chatclient.cpp \
           src/chatserver.cpp \
           src/chatwindow.cpp \
           src/loginwindow.cpp \
           src/main.cpp \
           src/mainwindow.cpp \
           src/messagewidget.cpp \
           src/test_avatar.cpp \
           build/rcc/qrc_qtchat.cpp \
           src/client/main.cpp \
           src/db/db.cpp \
           src/models/friendmodel.cpp \
           src/models/groupmodel.cpp \
           src/models/usermodel.cpp \
           src/server/chatserver.cpp \
           src/server/chatservice.cpp \
           src/server/main.cpp \
           test/testjson/obtestjson.cpp \
           test/testjson/testjson.cpp \
           test/testmuduo/muduo_server.cpp \
           src/server/db/db.cpp \
           src/server/model/emojimodel.cpp \
           src/server/model/friendmodel.cpp \
           src/server/model/groupmodel.cpp \
           src/server/model/offlinemessagemodel.cpp \
           src/server/model/usermodel.cpp \
           src/server/redis/redis.cpp \
           build/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
           build/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/src/client/ChatClient_autogen/mocs_compilation.cpp \
           build/src/client/QtChat_autogen/mocs_compilation.cpp \
           build/src/server/ChatServer_autogen/mocs_compilation.cpp \
           src/server/build/ChatServer_autogen/mocs_compilation.cpp \
           build/src/client/QtChat_autogen/VNU7RW3YIC/qrc_qtchat.cpp \
           src/server/build/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
           src/server/build/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.c \
           test/testmuduo/bulid/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
RESOURCES += src/qtchat.qrc
TRANSLATIONS += build/src/client/CMakeFiles/ChatClient.dir/compiler_depend.ts \
                build/src/client/CMakeFiles/ChatClient_autogen.dir/compiler_depend.ts \
                build/src/client/CMakeFiles/ChatClient_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/src/client/CMakeFiles/QtChat.dir/compiler_depend.ts \
                build/src/client/CMakeFiles/QtChat_autogen.dir/compiler_depend.ts \
                build/src/client/CMakeFiles/QtChat_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/src/server/CMakeFiles/ChatServer.dir/compiler_depend.ts \
                build/src/server/CMakeFiles/ChatServer_autogen.dir/compiler_depend.ts \
                build/src/server/CMakeFiles/ChatServer_autogen_timestamp_deps.dir/compiler_depend.ts \
                src/server/build/CMakeFiles/ChatServer.dir/compiler_depend.ts \
                src/server/build/CMakeFiles/ChatServer_autogen.dir/compiler_depend.ts \
                src/server/build/CMakeFiles/ChatServer_autogen_timestamp_deps.dir/compiler_depend.ts \
                test/testmuduo/bulid/CMakeFiles/server.dir/compiler_depend.ts
