#ifndef PUBLIC_H
#define PUBLIC_H

enum MsgType {
    LOGIN_MSG = 1,
    LOGIN_MSG_ACK = 2,
    LOGINOUT_MSG = 3,
    REG_MSG = 4,
    REG_MSG_ACK = 5,
    ONE_CHAT_MSG = 6,
    ADD_FRIEND_MSG = 7,
    ADD_FRIEND_MSG_ACK = 8,
    QUERY_FRIEND_MSG = 9,
    QUERY_FRIEND_MSG_ACK = 10,
    QUERY_GROUP_MSG = 11,
    QUERY_GROUP_MSG_ACK = 12,
    CREATE_GROUP_MSG = 13,
    CREATE_GROUP_MSG_ACK = 14,
    ADD_GROUP_MSG = 15,
    ADD_GROUP_MSG_ACK = 16,
    GROUP_CHAT_MSG = 17,
    INVITE_GROUP_MSG = 18,
    INVITE_GROUP_MSG_ACK = 19,

    CREATE_INTERVIEW_GROUP_MSG = 50,

    FILE_TRANSFER_REQ = 20,
    FILE_TRANSFER_ACK = 21,
    FILE_TRANSFER_DATA = 22,
    FILE_TRANSFER_COMPLETE = 23,
    FILE_TRANSFER_ERROR = 24,

    UPLOAD_EMOJI_MSG = 25,
    UPLOAD_EMOJI_MSG_ACK = 26,
    QUERY_EMOJI_LIST_MSG = 27,
    QUERY_EMOJI_LIST_MSG_ACK = 28,

    UPLOAD_AVATAR_MSG = 40,
    UPLOAD_AVATAR_MSG_ACK = 41,
    UPDATE_AVATAR_MSG = 42,
    UPDATE_AVATAR_MSG_ACK = 43,

    STATE_UPDATE_MSG = 44,

    VOICE_MSG = 60
};

constexpr const char* TABLE_USER = "user";
constexpr const char* TABLE_FRIEND = "friend";
constexpr const char* TABLE_ALLGROUP = "allgroup";
constexpr const char* TABLE_GROUPUSER = "groupuser";
constexpr const char* TABLE_OFFLINEMESSAGE = "offlinemessage";

static const int DEFAULT_SERVER_PORT = 8000;

#endif
